trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Or '20.x' for newer versions
  displayName: 'Install Node.js'

- script: |
    #!/bin/bash
    echo "Current working directory:"
    pwd
    cd $(System.DefaultWorkingDirectory)
    echo "Installing dependencies..."
    npm install

    echo "Running ESLint..."
    npx eslint .

    echo "Running Jest tests..."
    npm test

    if [ $? -ne 0 ]; then
      echo "Validation or testing failed."
      exit 1
    else
      echo "Validation and testing successful."
      exit 0
    fi
  displayName: 'Validation and Testing'
