# Azure DevOps Pipeline Example for Linux vm.ps1 validation

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Run vm.ps1 and capture errors'
  inputs:
    targetType: 'filePath'
    filePath: 'vm.ps1'
    arguments: '2>&1' # Redirect stderr to stdout
  continueOnError: true # Allow pipeline to continue even if the script fails

- task: Bash@3
  displayName: 'Check for errors in script output'
  condition: succeededOrFailed() # Run regardless of the previous step's outcome
  inputs:
    targetType: 'inline'
    script: |
      if [[ -n "$(< vm.ps1)" ]]; then
        echo "Script output:"
        cat vm.ps1
      fi
      if grep -q "error" vm.ps1; then
        echo "##vso[task.logissue type=error]Errors found in vm.ps1 output."
        exit 1 # Fail the task
      else
        echo "No errors found in vm.ps1 output."
      fi

