# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: 'Install PSScriptAnalyzer'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

- task: PowerShell@2
  displayName: 'Run PSScriptAnalyzer'
  inputs:
    targetType: 'inline'
    script: |
      Invoke-ScriptAnalyzer -Path . -Settings .\PSScriptAnalyzerSettings.psd1 -ErrorAction Stop
