trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest' if you prefer

steps:
- task: PowerShell@2
  displayName: 'Display Git Diffs'
  inputs:
    targetType: 'inline'
    script: |
      # Get the commit ID of the previous commit
      $previousCommit = git rev-parse HEAD^

      # Get the list of changed PowerShell files
      $changedFiles = git diff --name-only $previousCommit HEAD -- '*.ps1'

      # Display the diff for each changed PowerShell file
      if ($changedFiles) {
        foreach ($file in $changedFiles) {
          Write-Host "Changes to $file:"
          $diff = git diff $previousCommit HEAD -- $file
          if ($diff) {
            Write-Host $diff
          } else {
            Write-Host "No changes to $file."
          }
        }
      } else {
        Write-Host "No changes to PowerShell files in this commit."
      }
