trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest' if you prefer

steps:
- task: PowerShell@2
  displayName: 'Display Git Diff'
  inputs:
    targetType: 'inline'
    script: |
      # Get the commit ID of the previous commit
      $previousCommit = git rev-parse HEAD^

      # Get the diff between the current commit and the previous commit
      $diff = git diff $previousCommit HEAD -- vm.ps1

      # Display the diff
      if ($diff) {
        Write-Host "Changes to vm.ps1:"
        Write-Host $diff
      } else {
        Write-Host "No changes to vm.ps1 in this commit."
      }
