trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest' if you prefer

steps:
- task: PowerShell@2
  displayName: 'Display Git Diff'
  inputs:
    targetType: 'inline'
    script: |
      # Check if HEAD^ exists
      $previousCommit = git rev-parse HEAD^ 2>$null

      if ($previousCommit) {
          # HEAD^ exists, so proceed with diff
          $diff = git diff $previousCommit HEAD -- vm.ps1

          if ($LASTEXITCODE -eq 0) {
              if ($diff) {
                  Write-Host "Changes to vm.ps1:"
                  Write-Host $diff
              } else {
                  Write-Host "No changes to vm.ps1 in this commit."
              }
          } else {
              Write-Error "Failed to get diff: $diff"
              exit 1
          }
      } else {
          # HEAD^ does not exist (first commit), so display a message
          Write-Host "First commit detected. No previous commit to diff against."
      }
