trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Install PowerShell Core
      sudo apt-get update
      sudo apt-get install -y powershell

      # Install PSScriptAnalyzer
      pwsh -Command "Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force"

      # Lint PowerShell files
      pwsh -Command "Invoke-ScriptAnalyzer -Path ./*.ps1 -Recurse -Severity Warning, Error"
      if ($LASTEXITCODE -ne 0) {
        echo "PSScriptAnalyzer found issues."
        exit 1
      } else {
        echo "PSScriptAnalyzer found no issues."
      }

  displayName: 'Validate PowerShell'
