trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Check PowerShell Syntax'
  inputs:
    targetType: 'filePath'
    filePath: 'vm.ps1'
    arguments: '-ErrorAction Stop' # Ensures the script stops on the first error
    errorActionPreference: 'stop'
    pwsh: true # Use PowerShell Core for better compatibility

- task: PowerShell@2
  displayName: 'Run Script with -SyntaxCheck'
  inputs:
    targetType: 'inline'
    script: 'powershell -NoProfile -Command { Test-Path vm.ps1; if ($?) { powershell -NoProfile -SyntaxCheck vm.ps1 } }'
    errorActionPreference: 'stop'
    pwsh: true
