# Azure DevOps Pipeline Example for Linux vm.ps1 validation (Corrected and Bash-free)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: 'Install Az Module'
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Az -AllowClobber -Scope CurrentUser'

- task: PowerShell@2
  displayName: 'Run vm.ps1'
  inputs:
    targetType: 'filePath'
    filePath: 'vm.ps1'
