trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'e5b9c9ca-9260-4003-886c-fa7ab3b5fb9a' #Replace with your service connection.
    ScriptType: 'InlineScript'
    Inline: 'Connect-AzAccount -Identity' #Uses managed identity if available

- task: AzurePowerShell@5
  displayName: 'Create Resource Group'
  inputs:
    azureSubscription: 'e5b9c9ca-9260-4003-886c-fa7ab3b5fb9a #Replace with your service connection.
    ScriptType: 'FilePath'
    ScriptPath: 'rg.ps1'
    FailOnStderr: true #Fail the task if any errors are written to the error stream.

- task: AzurePowerShell@5
  displayName: 'Validate Resource Group'
  inputs:
    azureSubscription: 'e5b9c9ca-9260-4003-886c-fa7ab3b5fb9a' #Replace with your service connection.
    ScriptType: 'FilePath'
    ScriptPath: 'validate_rg.ps1'
    FailOnStderr: true

- task: AzurePowerShell@5
  displayName: 'Cleanup (Optional)'
  condition: succeeded() #Only run if the previous tasks succeed
  inputs:
    azureSubscription: 'e5b9c9ca-9260-4003-886c-fa7ab3b5fb9a' #Replace with your service connection.
    ScriptType: 'InlineScript'
    Inline: 'Remove-AzResourceGroup -Name powershell_resource-group -Force -ErrorAction SilentlyContinue'
